[build]
builder = "nixpacks"
buildCommand = "chmod +x start.sh"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.resources]
cpu = 1000
memory = 512
volumes = [
  {mountPath = "/data", size = 512}
]

[[services]]
name = "yt-stream"
envVars = [
  "YOUTUBE_KEY"
]

[metrics]
enabled = true
port = 3000
path = "/metrics"
