[build]
builder = "nixpacks"
buildCommand = "chmod +x ./start.sh"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "yt-stream"
processes = ["app"]

[services.concurrency]
type = "connections"
soft_limit = 100
hard_limit = 150

[services.resources]
cpu = 0.5
memory = 512
storage = 512

[services.env]
YOUTUBE_KEY = "${YOUTUBE_KEY}"

[services.ports]
http = 80

[services.metrics]
enabled = true
path = "/metrics"
