[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "yt-stream"
protocol = "tcp"
internal_port = 80

[services.concurrency]
hard_limit = 1
soft_limit = 1

[services.resources]
memory = 512
cpu = 500

[services.env]
YOUTUBE_KEY = "${YOUTUBE_KEY}"
