[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internal_port = 80
num_instances = 1

# Resource constraints to stay within Railway $5 credit
[service.resources]
memory = 512
cpu = 1000

[env]
NODE_ENV = "production"
