[[services]]
name = "yt-stream"
dockerfile = "Dockerfile"

[services.environment]
YOUTUBE_KEY = "${YOUTUBE_KEY}"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build]
builder = "dockerfile"
buildCommand = "chmod +x start.sh"

[services.resources]
cpu = 0.5
memory = 512
temp_storage = 512
