[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
YOUTUBE_KEY = "CONFIGURE_THIS"

[[services]]
name = "yt-stream"
internal_port = 8080
protocol = "tcp"

[services.resources]
memory = 512
cpu = 0.5
